implemented shape
eltorocorp/rust-s2 pull request #9
Opened 2019-06-10 14:56 UTC by haynes1

2019-06-10 17:11 UTC, crgant12 requested changes

2019-06-10 17:11 UTC, crgant12 commented on src/s2/shape.rs
> +pub fn sortEdges(e: Vec<Edge>) -> Vec<Edge> {
This probably needs to be done like this example https://rust-lang-nursery.github.io/rust-cookbook/algorithms/sorting.html

2019-06-10 17:11 UTC, crgant12 commented on src/s2/shape.rs
> +	pub fn Len(&self, ) -> i64 { len(self) }
This is for go's way of sorting things. You probably don't need this.

2019-06-10 17:11 UTC, crgant12 commented on src/s2/shape.rs
> +	privateInterface()
I would just take this out since it doesn't translate directory from go.

2019-06-10 17:11 UTC, crgant12 commented on src/s2/shape.rs
> +	fn NumEdges() -> i64;
Rename all of these the rust way.

2019-06-12 20:32 UTC, crgant12 requested changes

2019-06-12 20:32 UTC, crgant12 commented on src/r2/point.rs
> +impl Eq for Point {}
Delete this since you're not implementing it.

2019-06-12 20:32 UTC, crgant12 commented on src/r2/point.rs
> +
Delete all of the blank lines

2019-06-13 13:23 UTC, haynes1 commented on src/r2/point.rs
> +impl Eq for Point {}
This needs to stay. I agree its weird that you have to impl something that has no methods
https://doc.rust-lang.org/std/cmp/trait.Eq.html

2019-06-13 13:25 UTC, crgant12 approved these changes

2019-06-13 13:27 UTC, merged